fastcampus-team4/KDT3-M4

- src/Router.jsx
- src/components/login/LogIn.jsx
- src/components/signup/SignUp.jsx
- src/components/total-product/Product.jsx
- src/components/total-product/Product.module.css
- src/components/total-product/TotalProduct.jsx
- src/components/total-product/TotalProduct.module.css
- src/components/total-product/fetch.js
- src/data/API.jsx
- src/data/authApi.jsx
- src/pages/Detail.jsx
- src/pages/Home.jsx
resolve #21 
**API 로 전체 상품 정보 화면에 출력**
> 221205 Link to API

- package.json
- src/Router.jsx
- src/components/gnb/GNB.jsx
- src/components/gnb/GNB.module.css
- src/components/gnb/GnbDepth.jsx
- src/components/gnb/GnbDepth.module.css
- src/components/gnb/PageLink.jsx
- src/components/header/Header.jsx
- src/pages/Home.jsx
- src/pages/NotFound.jsx
- src/pages/Root.jsx
- src/pages/categories/AgriculturalProducts.jsx
- src/pages/categories/AllProducts.jsx
- src/pages/categories/Best.jsx
- src/pages/categories/DriedFish.jsx
- src/pages/categories/Fruits.jsx
- src/pages/categories/Grain.jsx
- src/pages/categories/Honey.jsx
- src/pages/categories/LivestockProducts.jsx
- src/pages/categories/MarineProducts.jsx
- src/pages/categories/OrdinaryProcessed.jsx
- src/pages/categories/ProcessedFood.jsx
- src/pages/categories/SesonalMarine.jsx
- src/pages/categories/SideDish.jsx
- src/pages/categories/Snack.jsx
- src/pages/categories/SweetPotato.jsx
- src/pages/categories/Tea.jsx
- src/pages/categories/Vegetables.jsx
> Create a Gnb component

- src/Router.jsx
- src/components/Button/Button.jsx
- src/components/Button/Button.module.css
- src/components/KV/SliderContent.jsx
- src/components/total-product/Product.jsx
- src/components/total-product/TotalProduct.jsx
- src/components/total-product/fetch.js
- src/global.css
- src/pages/Detail.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductDetail.module.css
> 상품 상세페이지 구현

- src/components/CartItem/CartItem.jsx
- src/pages/MyCart.jsx
- src/pages/ProductDetail.jsx
useMutation() 사용해서 실시간으로 업데이트시켜줌
> fix: 상품 수량 추가 및 삭제 실시간으로 업데이트할 수 있도록 함

- src/api/firebase.js
- src/components/CartItem/CartItem.jsx
- src/pages/MyCart.jsx
- src/pages/ProductDetail.jsx
- yarn.lock
> 장바구니 유저정보 불러오는거 해경님꺼로 적용함

- src/Router.jsx
- src/components/header/Header.jsx
- src/pages/Home.jsx
- src/pages/Search.jsx
- yarn.lock
close #40
fix #40
- useSearchParams 이용하여 주소의 search 로 페이지 감지
> 221214 Resolving netlify errors

- src/components/header/Header.jsx
- src/components/header/Header.module.css
> modify header component

- src/api/firebase.js
- src/components/CartItem/CartItem.jsx
- src/pages/MyCart.jsx
- src/pages/MyCart.module.css
- src/pages/ProductDetail.jsx
#36
상품 선택 기능 구현 및 선택된 상품들을 구매 페이지로 데이터 보내주는 것까지 구현했으나 상품 선택과정에 있어서 약간의 오류가 있어서 수정할 예정입니다.
추가로 장바구니 페이지에 들어왔을 때, 상품이 모두 선택되어 있도록 변경할 예정입니다.
> feat: Create my Cart select button function

- src/Router.jsx
- src/hooks/useCart.jsx
- src/pages/ProductDetail.jsx
> fix: user 정보 받아오는 상태 수정

- src/components/header/Header.jsx
- yarn.lock
관리자 계정이 로그인 할 경우 관리자 전용 페이지로 이동하는 카테고리 생성
> add admin category in header

- src/pages/MyBuy.jsx
- src/pages/MyBuy.module.css
resolve #60 
수정한 게 안 올라가서 다시 pull request 했습니다
> 221219 Retrieve the value of isSoldOut and fix it

- package-lock.json
- package.json
- src/components/CartItem/CartItem.jsx
- src/components/CartItem/CartItem.module.css
- src/components/kv/Slider.module.css
- src/components/kv/SliderContent.jsx
- src/components/total-product/TotalProduct.jsx
- src/data/API.jsx
- src/pages/MyCart.jsx
- src/pages/ProductDetail.jsx
- yarn.lock
- 장바구니
1. isSoldOut 속성 추가함
2. 품절일 상품의 경우, 해당 상품 블러 처리 함
3. 품절일 상품의 경우, 개별 주문하기 버튼 클릭 시, alert창 나오고 구매페이지로 이동 안함
4. 품절인 상품의 경우, 수량 증감 버튼 및 체크박스 작동하지 않음
5. 선택된 상품 중 품절인 상품이 있다면, 품절된 상품을 제외한 나머지 상품들만 구매페이지로 데이터가 전달됨
6. 선택된 상품과 품절이 아닌 상품의 금액, 갯수가 보여지도록 수정함
7. 아무것도 선택되지 않았을 경우 배송비는 0원으로 보이게 함
1. 전체체크 버튼 로직 수정
2. 해당 상품 클릭 시, 상품 상세 페이지로 이동
3. 선택상품 삭제 기능
4. 품절된 상품 삭제 기능
5. 장바구니 추가 순으로 정렬
isSoldOut 키가 추가되었으므로 기존 장바구니 상품들 전부 삭제 시킨 후에 추가되는 제품부터 위의 기능이 적용함
> fix: myCart Page

- src/components/recentlyViewed/RecentlyViewed.jsx
최근 본 상품에 제품이 없을 경우 에러 발생함
```javascript
if(watchedProducts) {
for(let products of watchedProducts){
let details = getProductDetail(products)
details.then((data) => {
setProducts((curArr)=>[data, ...curArr])
});
}
}
```
if문을 통해 에러를 해결함
> fix recentlyViewed component

- src/api/firebase.js
- src/components/CartItem/CartItem.jsx
- src/pages/MyBuy.jsx
구매하기 페이지에서 구매된 상품 장바구니에서 삭제하기 구현
> fix: myBuy page

- src/api/firebase.js
- src/hooks/useCart.jsx
- src/pages/MyBuy.jsx
useCart Hooks에 removeItems 추가
구매페이지에서만 사용하는 로직
> fix: useCart Hooks

- src/pages/MyBuy.jsx
단일 상품 구매 시 상품과 장바구니 상품 구매 시 상품을 구분한 부분의 코드가 삭제되어 수정
> 221222 단일 상품 구매 상품 정보 나오지 않는 것 수정

- src/components/buy/BuyItem.jsx
- src/pages/MyBuy.jsx
> 221222 단일 상품 구매 상품 정보 나오지 않는 것 수정 2

- src/pages/MyBuy.jsx
- src/pages/ProductDetail.jsx
- 상품 정보 분류한 변수 수정 후 단일 구매 상품 정보 나오지 않던 것 ProductDetail 에서 배열로 수정
- 구매하기 페이지에서 화면에 출력될 가격들 or 연산자로 해결
> 221226 Edit product information classification

- src/api/productApi.js
- src/components/admin/TransactionCard.jsx
- src/components/admin/TransactionCard.module.css
- src/pages/admin/Transactions.jsx
거래내역 피이지 기능 구현 완료
- pending, done, cancel 버튼 클릭시 동기적으로 active 전환 
- 버튼 클릭마다 비동기적으로 서버에 수정 데이터 전송
- 모든거래내역 데이터를 서버에서 받아와서 랜더링 하는 기능 
- overview 정보를 표현하는 로직구현
> feat: 거래내역페이지 기능구현 완

- test1.js
> hard reset (지원님 커밋취소)

- src/api/accountApi.js
- src/api/productApi.js
- src/components/my-buy/AddressForm.jsx
- src/components/my-buy/AddressForm.module.css
- src/components/my-buy/DeliveryForm.jsx
- src/components/my-buy/DeliveryForm.module.css
- src/components/total-product/Product.module.css
- src/pages/my-buy/MyBuy.jsx
Reverts fastcampus-team4/KDT3-M4#133
> Revert "230112 Refactoring done"

- src/components/my-cart/CartItem.jsx
- src/components/my-cart/PriceCard.jsx
- src/pages/my-cart/MyCart.jsx
- src/pages/products/ProductDetail.jsx
> Fix: Update checkbox logic in cart page

- src/App.jsx
- src/components/footer/Footer.jsx
- src/components/header/Header.jsx
- src/components/header/Header.module.css
- src/pages/home/Home.jsx
> feat: footer

- package-lock.json
- src/api/commonApi.js
- src/api/productApi.js
- src/components/header/Header.jsx
- src/components/my-page/MyOrder.jsx
1. 비로그인상태일 때 헤더 안나오는 에러 수정
그냥 is Loading 일때 return 만 지워도 될거같긴한데,, 
일단 로그인일때 -> account 랑 장바구니, 비로그인 -> 로그인 버튼 생성되도록 수정하고 return 구문도 지웠습니다.
2. 마이페이지 myorder 에러 수정
주문내역없을 때 length값 없어서 처음에 에러났네요. 수정했습니다.!
> Fix : header error

- src/components/admin/ProductCard.jsx
- src/components/home/Bestseller.jsx
- src/components/home/_prod.json
- product id 변경으로 슬라이더의 링크가 제대로 작동하지 않는 부분 수정
- admin/products 페이지에서 상품카드에서 상세페이지로 가는 기능 추가
> fix: slider linksr in Home

- src/components/my-page/AddAccount.jsx
- src/components/my-page/TransactionDetail.jsx
- src/pages/login/LogIn.jsx
close #168 
마지막으로 주문상세 내역에서 주문확정/취소 하면 바로 반영되도록 
useMutation, invalidateQuries 써서 구현했습니당..
> Fix : order confirm/cancel useMutation

- src/Router.jsx
- src/api/adminUser.js
- src/components/header/Header.jsx
헤더에 어드민 페이지 링크 추가
어드민 페이지 라우터 보호
> Fix: Add admin page Link in Header
